ALTER TABLE "Schedule"
ADD COLUMN "isPublic" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "ScheduleOverride"
ADD COLUMN "isPublic" BOOLEAN;

ALTER TYPE "OverrideType" ADD VALUE IF NOT EXISTS 'VISIBLE';
ALTER TYPE "OverrideType" ADD VALUE IF NOT EXISTS 'HIDDEN';
